// Generated by rstantools.  Do not edit by hand.

/*
    jaspTimeSeries is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    jaspTimeSeries is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with jaspTimeSeries.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_binomialLocalLevelRegression_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 47> locations_array__ =
  {" (found before start of program)",
  " (in 'binomialLocalLevelRegression', line 21, column 2 to column 32)",
  " (in 'binomialLocalLevelRegression', line 23, column 2 to column 26)",
  " (in 'binomialLocalLevelRegression', line 25, column 2 to column 20)",
  " (in 'binomialLocalLevelRegression', line 27, column 2 to column 17)",
  " (in 'binomialLocalLevelRegression', line 30, column 2 to column 15)",
  " (in 'binomialLocalLevelRegression', line 31, column 2 to column 15)",
  " (in 'binomialLocalLevelRegression', line 32, column 2 to column 18)",
  " (in 'binomialLocalLevelRegression', line 33, column 2 to column 18)",
  " (in 'binomialLocalLevelRegression', line 35, column 2 to column 26)",
  " (in 'binomialLocalLevelRegression', line 37, column 2 to column 24)",
  " (in 'binomialLocalLevelRegression', line 38, column 2 to column 40)",
  " (in 'binomialLocalLevelRegression', line 40, column 2 to column 29)",
  " (in 'binomialLocalLevelRegression', line 42, column 2 to column 24)",
  " (in 'binomialLocalLevelRegression', line 45, column 2 to column 63)",
  " (in 'binomialLocalLevelRegression', line 47, column 2 to line 48, column 50)",
  " (in 'binomialLocalLevelRegression', line 49, column 2 to column 38)",
  " (in 'binomialLocalLevelRegression', line 55, column 4 to column 54)",
  " (in 'binomialLocalLevelRegression', line 54, column 9 to line 56, column 3)",
  " (in 'binomialLocalLevelRegression', line 53, column 4 to column 72)",
  " (in 'binomialLocalLevelRegression', line 52, column 43 to line 54, column 3)",
  " (in 'binomialLocalLevelRegression', line 52, column 9 to line 56, column 3)",
  " (in 'binomialLocalLevelRegression', line 51, column 4 to column 54)",
  " (in 'binomialLocalLevelRegression', line 50, column 36 to line 52, column 3)",
  " (in 'binomialLocalLevelRegression', line 50, column 2 to line 56, column 3)",
  " (in 'binomialLocalLevelRegression', line 57, column 2 to column 40)",
  " (in 'binomialLocalLevelRegression', line 6, column 2 to column 17)",
  " (in 'binomialLocalLevelRegression', line 7, column 8 to column 9)",
  " (in 'binomialLocalLevelRegression', line 7, column 2 to column 26)",
  " (in 'binomialLocalLevelRegression', line 8, column 8 to column 9)",
  " (in 'binomialLocalLevelRegression', line 8, column 2 to column 26)",
  " (in 'binomialLocalLevelRegression', line 9, column 2 to column 17)",
  " (in 'binomialLocalLevelRegression', line 10, column 9 to column 10)",
  " (in 'binomialLocalLevelRegression', line 10, column 12 to column 13)",
  " (in 'binomialLocalLevelRegression', line 10, column 2 to column 25)",
  " (in 'binomialLocalLevelRegression', line 12, column 2 to column 31)",
  " (in 'binomialLocalLevelRegression', line 13, column 2 to column 31)",
  " (in 'binomialLocalLevelRegression', line 14, column 2 to column 31)",
  " (in 'binomialLocalLevelRegression', line 15, column 2 to column 48)",
  " (in 'binomialLocalLevelRegression', line 16, column 2 to column 33)",
  " (in 'binomialLocalLevelRegression', line 17, column 2 to column 30)",
  " (in 'binomialLocalLevelRegression', line 25, column 9 to column 12)",
  " (in 'binomialLocalLevelRegression', line 27, column 9 to column 10)",
  " (in 'binomialLocalLevelRegression', line 30, column 9 to column 10)",
  " (in 'binomialLocalLevelRegression', line 31, column 9 to column 10)",
  " (in 'binomialLocalLevelRegression', line 32, column 9 to column 12)",
  " (in 'binomialLocalLevelRegression', line 33, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_binomialLocalLevelRegression final : public model_base_crtp<model_binomialLocalLevelRegression> {
private:
  int T;
  std::vector<int> n;
  std::vector<int> y;
  int K;
  Eigen::Matrix<double,-1,-1> predictor_data__;
  double prior_theta1_a;
  double prior_theta1_b;
  double prior_sigma_sd;
  int prior_beta_distribution;
  double prior_beta_scale;
  double prior_beta_df;
  int z_raw_1dim__;
  int eta_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> predictor{nullptr, 0, 0};
public:
  ~model_binomialLocalLevelRegression() {}
  model_binomialLocalLevelRegression(stan::io::var_context& context__,
                                     unsigned int random_seed__ = 0,
                                     std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_binomialLocalLevelRegression_namespace::model_binomialLocalLevelRegression";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 26;
      context__.validate_dims("data initialization", "T", "int",
        std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      current_statement__ = 26;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 27;
      stan::math::validate_non_negative_index("n", "T", T);
      current_statement__ = 28;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{static_cast<size_t>(T)});
      n = std::vector<int>(T, std::numeric_limits<int>::min());
      current_statement__ = 28;
      n = context__.vals_i("n");
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "n", n, 0);
      current_statement__ = 29;
      stan::math::validate_non_negative_index("y", "T", T);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(T)});
      y = std::vector<int>(T, std::numeric_limits<int>::min());
      current_statement__ = 30;
      y = context__.vals_i("y");
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 31;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 31;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("predictor", "T", T);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("predictor", "K", K);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "predictor", "double",
        std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(K)});
      predictor_data__ = Eigen::Matrix<double,-1,-1>::Constant(T, K,
                           std::numeric_limits<double>::quiet_NaN());
      new (&predictor)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(predictor_data__.data(), T,
        K);
      {
        std::vector<local_scalar_t__> predictor_flat__;
        current_statement__ = 34;
        predictor_flat__ = context__.vals_r("predictor");
        current_statement__ = 34;
        pos__ = 1;
        current_statement__ = 34;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 34;
          for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
            current_statement__ = 34;
            stan::model::assign(predictor, predictor_flat__[(pos__ - 1)],
              "assigning variable predictor", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 34;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 35;
      context__.validate_dims("data initialization", "prior_theta1_a",
        "double", std::vector<size_t>{});
      prior_theta1_a = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 35;
      prior_theta1_a = context__.vals_r("prior_theta1_a")[(1 - 1)];
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "prior_theta1_a",
        prior_theta1_a, 0);
      current_statement__ = 36;
      context__.validate_dims("data initialization", "prior_theta1_b",
        "double", std::vector<size_t>{});
      prior_theta1_b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 36;
      prior_theta1_b = context__.vals_r("prior_theta1_b")[(1 - 1)];
      current_statement__ = 36;
      stan::math::check_greater_or_equal(function__, "prior_theta1_b",
        prior_theta1_b, 0);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "prior_sigma_sd",
        "double", std::vector<size_t>{});
      prior_sigma_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 37;
      prior_sigma_sd = context__.vals_r("prior_sigma_sd")[(1 - 1)];
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__, "prior_sigma_sd",
        prior_sigma_sd, 0);
      current_statement__ = 38;
      context__.validate_dims("data initialization",
        "prior_beta_distribution", "int", std::vector<size_t>{});
      prior_beta_distribution = std::numeric_limits<int>::min();
      current_statement__ = 38;
      prior_beta_distribution = context__.vals_i("prior_beta_distribution")[(1
        - 1)];
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__,
        "prior_beta_distribution", prior_beta_distribution, 1);
      current_statement__ = 38;
      stan::math::check_less_or_equal(function__, "prior_beta_distribution",
        prior_beta_distribution, 3);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "prior_beta_scale",
        "double", std::vector<size_t>{});
      prior_beta_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 39;
      prior_beta_scale = context__.vals_r("prior_beta_scale")[(1 - 1)];
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "prior_beta_scale",
        prior_beta_scale, 0);
      current_statement__ = 40;
      context__.validate_dims("data initialization", "prior_beta_df",
        "double", std::vector<size_t>{});
      prior_beta_df = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 40;
      prior_beta_df = context__.vals_r("prior_beta_df")[(1 - 1)];
      current_statement__ = 40;
      stan::math::check_greater_or_equal(function__, "prior_beta_df",
        prior_beta_df, 0);
      current_statement__ = 41;
      z_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 41;
      z_raw_1dim__ = (T - 1);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("z_raw", "T - 1", z_raw_1dim__);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("beta", "K", K);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("nu", "T", T);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("mu", "T", T);
      current_statement__ = 45;
      eta_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 45;
      eta_1dim__ = (T - 1);
      current_statement__ = 45;
      stan::math::validate_non_negative_index("eta", "T - 1", eta_1dim__);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("theta", "T", T);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + z_raw_1dim__ + K;
  }
  inline std::string model_name() const final {
    return "model_binomialLocalLevelRegression";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_binomialLocalLevelRegression_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ theta1 = DUMMY_VAR__;
      current_statement__ = 1;
      theta1 = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0, 1, lp__);
      local_scalar_t__ sigma_eta = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_eta = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> z_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(z_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 3;
      z_raw = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(z_raw_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(eta_1dim__,
          DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 9;
      stan::model::assign(eta, stan::math::multiply(sigma_eta, z_raw),
        "assigning variable eta");
      current_statement__ = 10;
      stan::model::assign(nu, stan::math::logit(theta1),
        "assigning variable nu", stan::model::index_uni(1));
      current_statement__ = 11;
      stan::model::assign(nu,
        stan::math::add(
          stan::model::rvalue(nu, "nu", stan::model::index_uni(1)),
          stan::math::cumulative_sum(eta)), "assigning variable nu",
        stan::model::index_min_max(2, T));
      current_statement__ = 12;
      stan::model::assign(mu,
        stan::math::add(nu, stan::math::multiply(predictor, beta)),
        "assigning variable mu");
      current_statement__ = 13;
      stan::model::assign(theta, stan::math::inv_logit(mu),
        "assigning variable theta");
      {
        current_statement__ = 14;
        lp_accum__.add(stan::math::beta_lpdf<false>(theta1, prior_theta1_a,
                         prior_theta1_b));
        current_statement__ = 15;
        lp_accum__.add((stan::math::normal_lpdf<false>(sigma_eta, 0,
                          prior_sigma_sd) -
          stan::math::normal_lccdf(0, 0, prior_sigma_sd)));
        current_statement__ = 16;
        lp_accum__.add(stan::math::normal_lpdf<false>(z_raw, 0, 1));
        current_statement__ = 24;
        if (stan::math::logical_eq(prior_beta_distribution, 1)) {
          current_statement__ = 22;
          lp_accum__.add(stan::math::normal_lpdf<false>(beta, 0,
                           prior_beta_scale));
        } else {
          current_statement__ = 21;
          if (stan::math::logical_eq(prior_beta_distribution, 2)) {
            current_statement__ = 19;
            lp_accum__.add(stan::math::student_t_lpdf<false>(beta,
                             prior_beta_df, 0, prior_beta_scale));
          } else {
            current_statement__ = 17;
            lp_accum__.add(stan::math::cauchy_lpdf<false>(beta, 0,
                             prior_beta_scale));
          }
        }
        current_statement__ = 25;
        lp_accum__.add(stan::math::binomial_lpmf<false>(y, n, theta));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_binomialLocalLevelRegression_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double theta1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      theta1 = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0, 1, lp__);
      double sigma_eta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      sigma_eta = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> z_raw =
        Eigen::Matrix<double,-1,1>::Constant(z_raw_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      z_raw = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(z_raw_1dim__);
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<double,-1,1> nu =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> eta =
        Eigen::Matrix<double,-1,1>::Constant(eta_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> theta =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(theta1);
      out__.write(sigma_eta);
      out__.write(z_raw);
      out__.write(beta);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 9;
      stan::model::assign(eta, stan::math::multiply(sigma_eta, z_raw),
        "assigning variable eta");
      current_statement__ = 10;
      stan::model::assign(nu, stan::math::logit(theta1),
        "assigning variable nu", stan::model::index_uni(1));
      current_statement__ = 11;
      stan::model::assign(nu,
        stan::math::add(
          stan::model::rvalue(nu, "nu", stan::model::index_uni(1)),
          stan::math::cumulative_sum(eta)), "assigning variable nu",
        stan::model::index_min_max(2, T));
      current_statement__ = 12;
      stan::model::assign(mu,
        stan::math::add(nu, stan::math::multiply(predictor, beta)),
        "assigning variable mu");
      current_statement__ = 13;
      stan::model::assign(theta, stan::math::inv_logit(mu),
        "assigning variable theta");
      if (emit_transformed_parameters__) {
        out__.write(nu);
        out__.write(mu);
        out__.write(eta);
        out__.write(theta);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ theta1 = DUMMY_VAR__;
      current_statement__ = 1;
      theta1 = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, theta1);
      local_scalar_t__ sigma_eta = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_eta = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_eta);
      Eigen::Matrix<local_scalar_t__,-1,1> z_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(z_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(z_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(z_raw_1dim__),
        "assigning variable z_raw");
      out__.write(z_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable beta");
      out__.write(beta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "theta1", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma_eta",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "z_raw", "double",
        std::vector<size_t>{static_cast<size_t>(z_raw_1dim__)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ theta1 = DUMMY_VAR__;
      current_statement__ = 1;
      theta1 = context__.vals_r("theta1")[(1 - 1)];
      out__.write_free_lub(0, 1, theta1);
      local_scalar_t__ sigma_eta = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_eta = context__.vals_r("sigma_eta")[(1 - 1)];
      out__.write_free_lb(0, sigma_eta);
      Eigen::Matrix<local_scalar_t__,-1,1> z_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(z_raw_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_raw_flat__;
        current_statement__ = 3;
        z_raw_flat__ = context__.vals_r("z_raw");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= z_raw_1dim__; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(z_raw, z_raw_flat__[(pos__ - 1)],
            "assigning variable z_raw", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(z_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 4;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"theta1", "sigma_eta", "z_raw",
                "beta"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"nu", "mu", "eta", "theta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(z_raw_1dim__)},
                std::vector<size_t>{static_cast<size_t>(K)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(T)},
             std::vector<size_t>{static_cast<size_t>(T)},
             std::vector<size_t>{static_cast<size_t>(eta_1dim__)},
             std::vector<size_t>{static_cast<size_t>(T)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "theta1");
    param_names__.emplace_back(std::string() + "sigma_eta");
    for (int sym1__ = 1; sym1__ <= z_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_raw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "nu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= eta_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "eta" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "theta1");
    param_names__.emplace_back(std::string() + "sigma_eta");
    for (int sym1__ = 1; sym1__ <= z_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_raw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "nu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= eta_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "eta" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"theta1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_eta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(z_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(eta_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"theta1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_eta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(z_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(eta_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + 1) + z_raw_1dim__) + K);
    const size_t num_transformed = emit_transformed_parameters * ((((T + T) +
      eta_1dim__) + T));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + 1) + z_raw_1dim__) + K);
    const size_t num_transformed = emit_transformed_parameters * ((((T + T) +
      eta_1dim__) + T));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_binomialLocalLevelRegression_namespace::model_binomialLocalLevelRegression;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_binomialLocalLevelRegression_namespace::profiles__;
}
#endif
#endif
