# Copyright (C) 2013-2026 University of Amsterdam
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# Adapted from the module's JASP-generated wrapper pattern. This file was
# not generated by JASP; its defaults must match binomialStateSpace.qml.

#' Binomial State Space Models
#'
#' Estimate a changing success probability from successes and trials at
#' equally spaced time points. Optional continuous covariates have additive,
#' time-constant effects on the log-odds scale.
#'
#' @param data Optional data frame for execution outside JASP.
#' @param version Analysis version used by JASP's syntax interface.
#' @param successes,trials,time Assigned variables, supplied as one-sided
#'   formulas (for example, \code{successes = ~ events}). Time is optional;
#'   trials is used only when \code{trialsMode = "variable"}.
#' @param covariates Optional one-sided formula assigning continuous covariates,
#'   for example \code{covariates = ~ temperature + rainfall}. Each covariate
#'   is separately centered and divided by its sample standard deviation.
#' @param priorBetaDistribution Zero-centered coefficient prior: \code{"normal"},
#'   \code{"studentT"} (default), or \code{"cauchy"}.
#'   Applied independently to each coefficient with shared prior settings.
#'   Used only when covariates are assigned.
#' @param priorBetaNormalSD Positive Normal coefficient-prior standard deviation,
#'   default 1. Used only for the Normal prior.
#' @param priorBetaScale Positive Student t coefficient-prior scale, default
#'   0.5. For degrees of freedom greater than two, the standard deviation is
#'   \code{priorBetaScale * sqrt(priorBetaDf / (priorBetaDf - 2))}; otherwise,
#'   the prior has no finite variance. Used only for the Student t prior.
#' @param priorBetaDf Positive Student t degrees of freedom, default three.
#'   Fractional values are allowed. Used only for the Student t prior.
#' @param priorBetaCauchyScale Positive Cauchy coefficient-prior scale, default
#'   0.707. This is not a standard deviation. Used only for the Cauchy prior.
#' @param trialsMode Use \code{"variable"} or \code{"constant"} trials.
#' @param trialsConstant Trials per row in constant mode; one supports
#'   binary observations.
binomialStateSpace <- function(
    data = NULL,
    version = "0.96.3",
    advancedMcmcAdaptDelta = 0.97,
    advancedMcmcBurnin = 2000,
    advancedMcmcChains = 3,
    advancedMcmcMaxTreeDepth = 15,
    advancedMcmcSamples = 5000,
    advancedMcmcSeed = 1,
    advancedMcmcThin = 1,
    covariates = list(types = list(), value = list()),
    plotBeta = FALSE,
    posteriorDistPlot = FALSE,
    priorBetaCauchyScale = 0.707,
    priorBetaDf = 3,
    priorBetaDistribution = "studentT",
    priorBetaNormalSD = 1,
    priorBetaScale = 0.5,
    priorSigmaSD = 1,
    priorTheta1Shape1 = 1,
    priorTheta1Shape2 = 1,
    showBeta = FALSE,
    showMcmcSummary = FALSE,
    showSigma = TRUE,
    showTheta = FALSE,
    statePlot = TRUE,
    successes = list(types = list(), value = ""),
    time = list(types = list(), value = ""),
    trials = list(types = list(), value = ""),
    trialsConstant = 1,
    trialsMode = "variable") {

  defaultArgCalls <- formals(jaspTimeSeries::binomialStateSpace)
  defaultArgs     <- lapply(defaultArgCalls, eval)
  options         <- as.list(match.call())[-1L]
  options         <- lapply(options, eval, envir = parent.frame())
  defaults        <- setdiff(names(defaultArgs), names(options))
  options[defaults]    <- defaultArgs[defaults]
  options[["data"]]    <- NULL
  options[["version"]] <- NULL

  if (!jaspBase::jaspResultsCalledFromJasp() && !is.null(data))
    jaspBase::storeDataSet(data)

  optionsWithFormula <- c("successes", "trials", "time", "covariates")
  for (name in optionsWithFormula) {
    if (inherits(options[[name]], "formula"))
      options[[name]] <- jaspBase::jaspFormula(options[[name]], data)
  }

  return(jaspBase::runWrappedAnalysis("jaspTimeSeries", "binomialStateSpace",
                                     "binomialStateSpace.qml", options, version, FALSE))
}
